import { FaBeer } from "react-icons/fa";

export const initEntries = [
  { icon: <FaBeer />, value: "Beer" },
  { icon: "", value: Math.floor(Math.random() * 10) },
  { icon: "", value: Math.floor(Math.random() * 10) },
  { icon: "", value: Math.floor(Math.random() * 10) },
  { icon: "", value: Math.floor(Math.random() * 10) },
  { icon: "", value: Math.floor(Math.random() * 10) },
  { icon: "", value: Math.floor(Math.random() * 10) },
  { icon: "", value: Math.floor(Math.random() * 10) },
  { icon: "", value: Math.floor(Math.random() * 10) },
  { icon: "", value: Math.floor(Math.random() * 10) },
  { icon: "", value: null },
  { icon: "", value: null },
  { icon: "", value: null },
  { icon: "", value: Math.floor(Math.random() * 10) },
  { icon: "", value: Math.floor(Math.random() * 10) },
  { icon: "", value: Math.floor(Math.random() * 10) },
  { icon: "", value: Math.floor(Math.random() * 10) },
  { icon: "", value: Math.floor(Math.random() * 10) },
  { icon: "", value: Math.floor(Math.random() * 10) },
  { icon: "", value: Math.floor(Math.random() * 10) },
  { icon: "", value: null },
  { icon: "", value: null },
  { icon: "", value: null },
  { icon: "", value: Math.floor(Math.random() * 10) },
  { icon: "", value: Math.floor(Math.random() * 10) },
  { icon: "", value: Math.floor(Math.random() * 10) },
  { icon: "", value: Math.floor(Math.random() * 10) },
  { icon: "", value: Math.floor(Math.random() * 10) },
  { icon: "", value: Math.floor(Math.random() * 10) },
  { icon: "", value: Math.floor(Math.random() * 10) },
  { icon: "", value: null },
  { icon: "", value: null },
  { icon: "", value: null },
  { icon: "", value: Math.floor(Math.random() * 10) },
  { icon: "", value: Math.floor(Math.random() * 10) },
  { icon: "", value: Math.floor(Math.random() * 10) },
  { icon: "", value: Math.floor(Math.random() * 10) },
  { icon: "", value: Math.floor(Math.random() * 10) },
  { icon: "", value: Math.floor(Math.random() * 10) },
  { icon: "", value: Math.floor(Math.random() * 10) },
];
